# Generated by Django 5.0.2 on 2025-01-26 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('type', models.CharField(choices=[('animal', 'Животное'), ('service', 'Услуга'), ('mating', 'Вязка'), ('lost_found', 'Потеряно/Найдено')], max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто'), ('moderation', 'На модерации')], default='moderation', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('size', models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой')], max_length=10, verbose_name='Размер')),
                ('color', models.CharField(max_length=100, verbose_name='Окрас')),
                ('pedigree', models.BooleanField(default=False, verbose_name='Родословная')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Вакцинирован')),
                ('passport', models.BooleanField(default=False, verbose_name='Ветеринарный паспорт')),
                ('microchipped', models.BooleanField(default=False, verbose_name='Чипирован')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='announcements.announcement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Объявление о животном',
                'verbose_name_plural': 'Объявления о животных',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='announcements.announcementcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='announcements.announcementcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='announcements.announcement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявлений',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostFoundAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', 'Потеряно'), ('found', 'Найдено')], max_length=10, verbose_name='Тип')),
                ('date_lost_found', models.DateField(verbose_name='Дата потери/находки')),
                ('distinctive_features', models.TextField(verbose_name='Отличительные черты')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_details', to='announcements.announcement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Объявление о потере/находке',
                'verbose_name_plural': 'Объявления о потере/находке',
            },
        ),
        migrations.CreateModel(
            name='MatingAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mating_details', to='announcements.announcement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Объявление о вязке',
                'verbose_name_plural': 'Объявления о вязке',
            },
        ),
        migrations.CreateModel(
            name='ServiceAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('walking', 'Выгул'), ('grooming', 'Груминг'), ('training', 'Дрессировка'), ('veterinary', 'Ветеринарные услуги'), ('boarding', 'Передержка')], max_length=20, verbose_name='Тип услуги')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('certificates', models.TextField(blank=True, verbose_name='Сертификаты')),
                ('schedule', models.TextField(verbose_name='График работы')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='announcements.announcement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Объявление об услуге',
                'verbose_name_plural': 'Объявления об услугах',
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['type', 'status'], name='announcemen_type_1568b7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category'], name='announcemen_categor_767517_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['author'], name='announcemen_author__0e981a_idx'),
        ),
    ]
